'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'ko' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 번역 데이터
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Navigation
    'nav.home': '홈',
    'nav.about': '회사소개',
    'nav.services': '서비스',
    'nav.products': '제품',
    'nav.contact': '연락처',
    'nav.quote': '견적 문의',
    'nav.tagline': '신뢰할 수 있는 여과 및 정화 솔루션',
    
    // Hero Section
    'hero.badge': '혁신적인 엔지니어링 솔루션',
    'hero.title1': '신뢰할 수 있는',
    'hero.title2': '여과 및 정화 솔루션',
    'hero.description': '2000년 설립 이래 필터, 저장탱크, 이온교환기 등 고품질 여과 및 정화 설비를 제조하며, 현대엔지니어링, 포스코, 삼성물산 등 주요 기업과 파트너십을 맺고 있습니다.',
    'hero.contact': '프로젝트 문의',
    'hero.video': '회사 소개 영상',
    'hero.stats.experience': '년 경험',
    'hero.stats.factory': '㎡ 공장 규모',
    'hero.stats.iso': '인증 시스템',
    'hero.feature.iso': 'ISO 9001 인증',
    'hero.feature.iso.desc': '품질관리 시스템',
    'hero.feature.support': '24/7 지원',
    'hero.feature.support.desc': '기술지원 서비스',
    'hero.feature.custom': '맞춤형 설계',
    'hero.feature.custom.desc': '솔루션 제공',
    
    // Services Section (Legacy - keeping for compatibility)
    'services.title': '전문 여과 및 정화 솔루션',
    'services.subtitle': '필터, 저장탱크, 이온교환기 등 다양한 정화 설비를 설계, 제조, 설치까지 원스톱 서비스로 제공합니다.',
    'services.filter.title': '필터 & 코알레서',
    'services.filter.desc': 'Filter, Coalescer 및 Filteration Package',
    'services.tank.title': '저장탱크 & 배관',
    'services.tank.desc': 'Storage Tank, Piping Spool 및 Package',
    'services.ion.title': '이온교환 시스템',
    'services.ion.desc': 'Ion Exchanger 및 수처리 솔루션',
    'services.env.title': '환경 솔루션',
    'services.env.desc': 'Silencer, Activated Carbon Canister',
    'services.details': '자세히 보기',
    'services.cta.title': '맞춤형 솔루션이 필요하신가요?',
    'services.cta.desc': '우리의 전문가팀이 귀하의 특별한 요구사항에 맞는 최적의 솔루션을 제안해드립니다.',
    'services.cta.consult': '무료 상담 신청',
    'services.cta.portfolio': '포트폴리오 보기',
    
    // Portfolio Section
    'portfolio.badge': '포트폴리오',
    'portfolio.title': '프로젝트 실적',
    'portfolio.subtitle': '24년간 수행한 다양한 프로젝트와 성과를 확인하세요',
    'portfolio.projects.title': '주요 프로젝트',
    'portfolio.projects.subtitle': '현대엔지니어링, 포스코, 삼성물산 등 주요 기업과의 협력 프로젝트',
    'portfolio.gallery.title': '작업 현장 갤러리',
    'portfolio.gallery.subtitle': '현장 설치 및 시공 과정을 확인하세요',
    'portfolio.filter.all': '전체',
    'portfolio.filter.filter': '필터 시스템',
    'portfolio.filter.tank': '저장탱크',
    'portfolio.filter.ion': '이온교환',
    'portfolio.filter.env': '환경설비',
    'portfolio.project.view': '자세히 보기',
    'portfolio.project.client': '고객사',
    'portfolio.project.period': '수행기간',
    'portfolio.project.description': '프로젝트 개요',
    'portfolio.project.achievements': '주요 성과',
    'portfolio.back': '목록으로 돌아가기',
    'portfolio.stats.experience': '년 경험',
    'portfolio.stats.projects': '완료 프로젝트',
    'portfolio.stats.international': '해외 프로젝트',
    'portfolio.stats.clients': '주요 고객사',
    
    // Portfolio Gallery
    'portfolio.gallery.filter.all': '전체',
    'portfolio.gallery.filter.filter': '필터',
    'portfolio.gallery.filter.tank': '탱크',
    'portfolio.gallery.filter.env': '환경',
    'portfolio.gallery.stats.total': '총',
    'portfolio.gallery.stats.images': '개의 작업사진',
    'portfolio.gallery.stats.category': '분야',
    'portfolio.gallery.loading': '로딩 중...',
    'portfolio.gallery.load.more': '더 보기',
    'portfolio.gallery.title.modal': '갤러리',
    
    // Portfolio Page - Project Descriptions (Korean)
    'portfolio.project.goseong.desc': '고성 복합천연가스발전소의 소음기 및 필터 시스템 구축 프로젝트',
    'portfolio.project.andong.desc': '안동 복합화력발전소 2호기의 배기 소음기 및 구조물 시스템',
    'portfolio.project.waste.tank.desc': 'SK하이닉스 폐기물 저장탱크 시스템 구축',
    'portfolio.project.kleannara.desc': '클린나라 청주 소각시설 소음기 시스템',
    'portfolio.project.datacenter.desc': '부평 데이터센터 디젤발전기 배기 소음기 시스템',
    'portfolio.project.turkistan.desc': '카자흐스탄 터키스탄 복합화력발전소 응축수 배수탱크',
    'portfolio.project.rgo.desc': '재생 그린오일 경질 나프타 코알레서 및 중질유 필터',
    'portfolio.project.shuaibah.desc': '사우디아라비아 슈아이바 3 독립수처리 시설 도너 로딩 필터',
    'portfolio.project.jafurah.desc': '사우디아라비아 자프라 가스공급시스템 응축수 배수탱크',
    'portfolio.project.activated.carbon.desc': '대구광역시 활성탄 재생시설 호퍼 및 구조물',
    'portfolio.project.bangladesh.desc': '방글라데시 메그나가트 718MW 복합화력발전소 스팀 블로우아웃 소음기',
    'portfolio.project.posco.desc': '포스코 포항 3, 4호 고로 스택 소음기 유지보수',
    
    // Portfolio Page - Project Achievements (Korean)
    'portfolio.project.goseong.achievement1': '40인치~2인치 규모의 대형 소음기 5세트 제조',
    'portfolio.project.goseong.achievement2': 'ID3200X9150L, ID2200X4040L 등 다양한 규격 소음기 설계',
    'portfolio.project.goseong.achievement3': '발전소 환경 소음 기준 충족 및 안정성 확보',
    
    'portfolio.project.andong.achievement1': '14인치 규모의 배기 소음기 설계 및 제조',
    'portfolio.project.andong.achievement2': 'OD1853 X7270L 대형 소음기 제작',
    'portfolio.project.andong.achievement3': '6m X 6m x 25m 규모의 구조물 구축',
    
    'portfolio.project.waste.tank.achievement1': 'W2062 X D1262 X 4300L 규모의 저장탱크 3세트 제조',
    'portfolio.project.waste.tank.achievement2': '1인치~18인치 배관 시스템 구축',
    'portfolio.project.waste.tank.achievement3': 'SS275 재질의 내식성 확보',
    
    'portfolio.project.kleannara.achievement1': 'OD1400 X 3450L 규모의 소음기 제조',
    'portfolio.project.kleannara.achievement2': 'A516-60 재질 적용으로 내구성 확보',
    'portfolio.project.kleannara.achievement3': '2인치~8인치 배관 시스템 구축',
    
    'portfolio.project.datacenter.achievement1': '750A, 500A 규모의 배기 소음기 2세트 제조',
    'portfolio.project.datacenter.achievement2': 'OD1800x4500TL, OD1500x3200TL 대형 소음기 설계',
    'portfolio.project.datacenter.achievement3': '데이터센터 소음 기준 충족',
    
    'portfolio.project.turkistan.achievement1': 'GOST 표준 적용한 응축수 배수탱크 5세트 제조',
    'portfolio.project.turkistan.achievement2': 'A516-70 재질의 고품질 탱크 제작',
    'portfolio.project.turkistan.achievement3': '해외 프로젝트 성공적 수행',
    
    'portfolio.project.rgo.achievement1': 'ID1600x1500TL, ID14"x1800TL 규모의 필터 시스템',
    'portfolio.project.rgo.achievement2': '경질 나프타 코알레서 및 중질유 필터 4세트 제조',
    'portfolio.project.rgo.achievement3': 'A516-70 재질의 고성능 필터 설계',
    
    'portfolio.project.shuaibah.achievement1': '316SS 재질의 고급 필터 시스템 구축',
    'portfolio.project.shuaibah.achievement2': 'ID3"x300TLx2Set 규모의 필터 제조',
    'portfolio.project.shuaibah.achievement3': '해외 대형 프로젝트 성공적 수행',
    
    'portfolio.project.jafurah.achievement1': '9T/17T 규모의 응축수 배수탱크 제조',
    'portfolio.project.jafurah.achievement2': 'A516-70 재질의 고품질 탱크 설계',
    'portfolio.project.jafurah.achievement3': '사우디아라비아 ARAMCO 프로젝트 수행',
    
    'portfolio.project.activated.carbon.achievement1': 'ID1200x1000TL 규모의 호퍼 6세트 제조',
    'portfolio.project.activated.carbon.achievement2': 'A240-304 재질의 고급 호퍼 시스템',
    'portfolio.project.activated.carbon.achievement3': '환경시설 소음기 및 구조물 구축',
    
    'portfolio.project.bangladesh.achievement1': '24인치 규모의 대형 스팀 블로우아웃 소음기 제조',
    'portfolio.project.bangladesh.achievement2': 'ID3000x9000TL 규모의 소음기 설계',
    'portfolio.project.bangladesh.achievement3': '9T/17T/18.5Tons 규모의 대형 소음기 시스템',
    
    'portfolio.project.posco.achievement1': 'OD3009x13297L 규모의 대형 스택 소음기 2세트',
    'portfolio.project.posco.achievement2': '15.5톤 규모의 대형 소음기 시스템',
    'portfolio.project.posco.achievement3': '기존 시설 유지보수 및 성능 개선',
    
    // About Section
    'about.badge': '회사 소개',
    'about.title1': '24년 전통의 신뢰할 수 있는',
    'about.title2': '여과 정화 전문기업',
    'about.description': '2000년 설립 이래, 경인엔지니어링은 필터, 저장탱크, 이온교환기 등 여과 및 정화 설비 전문 제조업체로 현대엔지니어링, 포스코E&C, 삼성물산 등 주요 기업들과 파트너십을 맺으며 성장해왔습니다.',
    'about.partnership.title': '글로벌 파트너십',
    'about.partnership.desc': 'Purolite(UK) 이온교환수지, Calgon(USA) 활성탄 공식 대리점',
    'about.certification.title': '인증 시스템',
    'about.certification.desc': 'ISO 9001, 14001, 45001 품질/환경/안전보건 경영시스템 인증',
    'about.quality.title': '신뢰할 수 있는 품질',
    'about.quality.desc': 'ASME U Stamp 취득 진행 중, 체계적인 품질관리 시스템',
    'about.history': '회사 히스토리',
    'about.certificates': '인증서 보기',
    'about.numbers.title': '숫자로 보는 경인엔지니어링',
    'about.numbers.desc': '신뢰할 수 있는 실적과 성과를 확인하세요',

    // Services Page
    'services.badge': '전문 서비스',
    'services.hero.title': '전문 여과 및 정화 솔루션',
    'services.hero.subtitle': '24년간 축적된 기술력과 경험으로 고객의 요구사항에 맞는 최적의 솔루션을 제공합니다.',
    'services.capacity.title': '연간 생산능력',
    'services.capacity.subtitle': 'Filter & Coalescer, Filtration Packages, Silencer (with Vent Stack), Storage Tank, Piping Spool & Package, Activated Carbon Canister, Activated Carbon Filter, Ion Exchanger',
    'services.capacity.special': '⭐ Silencer와 Filter는 직접 설계 및 인허가 가능',
    'services.capacity.table.description': '제품명',
    'services.capacity.table.unit': '단위 생산능력',
    'services.capacity.table.year': '연간 생산능력',
    'services.capacity.table.special': '특별 능력',
    'services.capacity.stats.total': '총 연간 생산능력 (Ton)',
    'services.capacity.stats.products': '생산 제품 종류',
    'services.capacity.stats.design': '직접 설계 및 인허가',
    'services.capacity.stats.unit': '단위 생산능력 (Ton)',
    'services.capacity.special.design': '직접 설계 및 인허가',
    'services.capacity.special.custom': '맞춤형 설계',
    'services.products.title': '제품 상세 정보',
    'services.products.subtitle': '각 제품의 기술 사양과 특징을 확인하세요',
    'services.products.filter.title': '필터 & 코알레서',
    'services.products.filter.design': '직접 설계 및 인허가',
    'services.products.filter.desc': '고효율 여과 시스템으로 액체 내 불순물을 제거하고 유화된 물방울을 분리하는 장비입니다. 다양한 산업 분야에서 사용되며, 맞춤형 설계로 고객의 요구사항에 최적화된 솔루션을 제공합니다.',
    'services.products.filter.feature1': '고효율 여과 및 분리 성능',
    'services.products.filter.feature2': '다양한 재질 및 크기 지원',
    'services.products.filter.feature3': '자동화된 제어 시스템',
    'services.products.filter.feature4': '쉬운 유지보수 및 교체',
    'services.products.filter.spec1': '처리 용량',
    'services.products.filter.spec2': '압력 범위',
    'services.products.filter.spec3': '온도 범위',
    'services.products.filter.spec4': '여과 정밀도',
    'services.products.filter.spec5': '재질',
    'services.products.filter.spec6': '인증',
    'services.products.silencer.title': '사일런서 (벤트 스택 포함)',
    'services.products.silencer.design': '직접 설계 및 인허가',
    'services.products.silencer.desc': '배기 가스의 소음을 감소시키고 환경 오염을 방지하는 소음 제거 장비입니다. 다양한 산업 시설에서 사용되며, 환경 규제를 준수하면서 효율적인 소음 제거를 제공합니다.',
    'services.products.silencer.feature1': '20~40 dB(A) 소음 감소',
    'services.products.silencer.feature2': '배출가스 처리 기능',
    'services.products.silencer.feature3': '내식성 재질 사용',
    'services.products.silencer.feature4': '환경 규제 준수',
    'services.products.silencer.spec1': '처리 용량',
    'services.products.silencer.spec2': '소음 감소',
    'services.products.silencer.spec3': '재질',
    'services.products.silencer.spec4': '인증',
    'services.products.silencer.spec5': '환경 규제',
    'services.products.silencer.spec6': '유지보수',
    'services.products.tank.title': '저장 탱크',
    'services.products.tank.design': '맞춤형 설계',
    'services.products.tank.desc': '다양한 액체 및 가스를 저장하는 대용량 저장 탱크입니다. 화학 물질, 원유, 가스 등 다양한 물질의 안전한 저장을 위한 맞춤형 설계를 제공합니다.',
    'services.products.tank.feature1': '1~1000 m³ 용량 지원',
    'services.products.tank.feature2': '화학 저항성 코팅',
    'services.products.tank.feature3': '레벨 제어 시스템',
    'services.products.tank.feature4': '안전 릴리프 밸브',
    'services.products.tank.spec1': '용량',
    'services.products.tank.spec2': '압력 등급',
    'services.products.tank.spec3': '재질',
    'services.products.tank.spec4': '두께',
    'services.products.tank.spec5': '인증',
    'services.products.tank.spec6': '용접',
    'services.products.ion.title': '이온교환기',
    'services.products.ion.design': '맞춤형 설계',
    'services.products.ion.desc': '이온교환 수지를 이용하여 물의 경도, 실리카, TDS 등을 제거하는 수처리 장비입니다. Purolite 수지를 사용하여 고품질의 정수 시스템을 제공합니다.',
    'services.products.ion.feature1': 'Purolite 수지 사용',
    'services.products.ion.feature2': '자동 재생 시스템',
    'services.products.ion.feature3': 'PLC 제어 시스템',
    'services.products.ion.feature4': 'HSE 인증',
    'services.products.ion.spec1': '처리 용량',
    'services.products.ion.spec2': '수질 개선',
    'services.products.ion.spec3': '재생 주기',
    'services.products.ion.spec4': '재질',
    'services.products.ion.spec5': '인증',
    'services.products.ion.spec6': '제어',
    'services.products.desc.title': '제품 설명',
    'services.products.spec.title': '기술 사양',
    'services.tabs.features': '주요 특징',
    'services.tabs.specifications': '기술 사양',
    'services.tabs.process': '프로세스',
    'services.tabs.cta.title': '맞춤형 솔루션이 필요하신가요?',
    'services.tabs.cta.desc': '전문 엔지니어가 귀하의 요구사항에 맞는 최적의 솔루션을 제안해드립니다.',
    'services.tabs.cta.consult': '무료 상담 신청',
    'services.tabs.cta.portfolio': '포트폴리오 보기',
    'services.faq.title': '자주 묻는 질문',
    'services.faq.subtitle': '고객님들이 자주 문의하시는 내용을 정리했습니다.',
    'services.faq.q1': '서비스 견적은 어떻게 받을 수 있나요?',
    'services.faq.a1': '홈페이지의 "견적 문의" 버튼을 클릭하거나 직접 연락처로 문의해주세요. 프로젝트 요구사항을 상세히 알려주시면 정확한 견적을 제공해드립니다.',
    'services.faq.q2': '설치 및 시운전 서비스도 제공하나요?',
    'services.faq.a2': '네, 모든 제품에 대해 현장 설치, 시운전, 운전 교육까지 원스톱 서비스를 제공합니다. 전문 엔지니어가 현장에서 직접 지원합니다.',
    'services.faq.q3': '품질 보증 기간은 얼마나 되나요?',
    'services.faq.a3': '표준 제품은 1년, 맞춤형 제품은 2년의 품질 보증을 제공합니다. 정기 유지보수 서비스도 함께 제공됩니다.',
    'services.faq.q4': '해외 프로젝트도 수행하나요?',
    'services.faq.a4': '네, 동남아시아, 중동, 아프리카 등 다양한 해외 프로젝트를 수행하고 있습니다. 현지 파트너와 협력하여 성공적으로 완료합니다.',
    'services.faq.q5': '기술 지원은 어떻게 받을 수 있나요?',
    'services.faq.a5': '24/7 기술 지원 라인을 운영하고 있습니다. 전화, 이메일, 원격 접속을 통해 언제든지 기술 지원을 받으실 수 있습니다.',
    'services.contact.title': '프로젝트 문의',
    'services.contact.subtitle': '전문가와 상담하여 최적의 솔루션을 찾아보세요.',
    'services.contact.consult': '무료 상담 신청',
    'services.contact.quote': '견적 문의',
    'about.stats.experience': '년 경험',
    'about.stats.factory': '㎡ 공장 규모',
    'about.stats.iso': 'ISO 인증',
    'about.stats.newFactory': '김포 신공장',
    
    // About Page Additional Keys
    'about.values.title': '경영이념',
    'about.values.subtitle': '경인엔지니어링이 추구하는 가치와 철학',
    'about.values.customer.title': '고객 만족',
    'about.values.customer.desc': '고객의 요구사항을 최우선으로 생각하며, 최고의 품질과 서비스를 제공합니다.',
    'about.values.innovation.title': '기술 혁신',
    'about.values.innovation.desc': '지속적인 기술 개발과 혁신을 통해 산업 발전에 기여합니다.',
    'about.values.social.title': '사회 책임',
    'about.values.social.desc': '환경 보호와 사회 발전에 기여하는 지속가능한 경영을 실천합니다.',
    'about.values.talent.title': '인재 육성',
    'about.values.talent.desc': '우수한 인재를 육성하고, 구성원의 성장과 발전을 지원합니다.',
    'about.history.title': '회사 히스토리',
    'about.history.subtitle': '24년간의 성장 과정과 주요 이정표',
    'about.history.2000.title': '회사 설립',
    'about.history.2000.desc': '경인엔지니어링 설립, 여과 및 정화 설비 제조 시작',
    'about.history.2005.title': 'ISO 9001 인증',
    'about.history.2005.desc': '품질관리시스템 인증 획득',
    'about.history.2010.title': '해외 진출',
    'about.history.2010.desc': '동남아시아 시장 진출, 첫 해외 프로젝트 수행',
    'about.history.2015.title': 'ISO 14001 인증',
    'about.history.2015.desc': '환경경영시스템 인증 획득',
    'about.history.2020.title': 'ISO 45001 인증',
    'about.history.2020.desc': '안전보건경영시스템 인증 획득',
    'about.history.2024.title': '24주년',
    'about.history.2024.desc': '24년간 축적된 기술력과 경험으로 성장',
    'about.certifications.title': '인증서 및 등록증',
    'about.certifications.subtitle': '국제 표준을 준수하는 품질 관리 시스템과 공장 등록',
    'about.certifications.iso9001.title': 'ISO 9001',
    'about.certifications.iso9001.desc': '품질경영시스템',
    'about.certifications.iso9001.year': '2005년 획득',
    'about.certifications.iso14001.title': 'ISO 14001',
    'about.certifications.iso14001.desc': '환경경영시스템',
    'about.certifications.iso14001.year': '2015년 획득',
    'about.certifications.iso45001.title': 'ISO 45001',
    'about.certifications.iso45001.desc': '안전보건경영시스템',
    'about.certifications.iso45001.year': '2020년 획득',
    'about.certifications.factory.title': '공장등록증',
    'about.certifications.factory.desc': '제조업 등록',
    'about.certifications.factory.year': '공식 등록',
    'about.certifications.meaning.title': '인증서의 의미',
    'about.certifications.quality.title': '품질 보증',
    'about.certifications.quality.desc': 'ISO 9001 인증으로 체계적인 품질 관리 시스템을 통해 최고의 제품을 제공합니다.',
    'about.certifications.environment.title': '환경 친화',
    'about.certifications.environment.desc': 'ISO 14001 인증으로 환경 보호를 우선시하는 지속가능한 경영을 실천합니다.',
    'about.certifications.safety.title': '안전 보건',
    'about.certifications.safety.desc': 'ISO 45001 인증으로 직원과 고객의 안전과 건강을 최우선으로 보호합니다.',
    'about.partnerships.title': '글로벌 파트너십',
    'about.partnerships.subtitle': '세계적인 파트너들과의 협력 관계',
    'about.partnerships.purolite.title': 'Purolite (UK)',
    'about.partnerships.purolite.desc': '이온교환수지 공식 대리점으로 고품질 수처리 솔루션을 제공합니다.',
    'about.partnerships.purolite.item1': '고품질 이온교환수지',
    'about.partnerships.purolite.item2': '기술 지원 및 교육',
    'about.partnerships.purolite.item3': '맞춤형 솔루션 제공',
    'about.partnerships.calgon.title': 'Calgon (USA)',
    'about.partnerships.calgon.desc': '활성탄 공식 대리점으로 환경 친화적인 정화 솔루션을 제공합니다.',
    'about.partnerships.calgon.item1': '고품질 활성탄',
    'about.partnerships.calgon.item2': '환경 정화 솔루션',
    'about.partnerships.calgon.item3': '지속가능한 기술',
    'about.cta.title': '함께 성장할 파트너를 찾고 있습니다',
    'about.cta.subtitle': '24년간 축적된 기술력과 경험으로 귀하의 프로젝트 성공을 지원합니다.',
    'about.cta.contact': '문의하기',
    'about.cta.services': '서비스 보기',
    'about.stats.projects': '완료 프로젝트',
    'about.stats.international': '해외 프로젝트',
    'about.stats.clients': '주요 고객사',
    
    // Contact Section
    'contact.badge': '연락처',
    'contact.title': '프로젝트 상담 및 문의',
    'contact.subtitle': '전문가와 직접 상담하고 맞춤형 솔루션을 제안받으세요. 빠른 답변을 위해 최선을 다하겠습니다.',
    'contact.form.title': '견적 문의하기',
    'contact.form.name': '성명',
    'contact.form.phone': '연락처',
    'contact.form.email': '이메일',
    'contact.form.company': '회사명',
    'contact.form.message': '문의내용',
    'contact.form.submit': '문의 보내기',
    'contact.info.title': '연락처 정보',
    'contact.info.desc': '언제든지 편하게 연락주세요. 전문 상담팀이 신속하게 답변드리겠습니다.',
    'contact.phone': '전화번호',
    'contact.email': '이메일',
    'contact.address': '공장 주소',
    'contact.size': '공장 규모',
    'contact.map.title': '오시는 길',
    'contact.map.desc': '지도 보기를 클릭하시면 상세한 위치를 확인하실 수 있습니다.',
    'contact.map.view': '지도 보기 →',
    
    // Contact Page
    'contact.page.badge': '연락처',
    'contact.page.title': '문의 및 연락처',
    'contact.page.subtitle': '24년간 축적된 기술력과 경험으로 고객의 요구사항에 맞는 최적의 솔루션을 제공합니다.',
    'contact.info.phone.title': '전화',
    'contact.info.phone.value': '031-987-6127',
    'contact.info.phone.desc': '평일 09:00~18:00',
    'contact.info.fax.title': '팩스',
    'contact.info.fax.value': '031-988-6128',
    'contact.info.contactPerson.title': '담당자',
    'contact.info.contactPerson.value': 'Technical Sales 팀의 Team Manager Mac Kim',
    'contact.info.mobile.title': '모바일',
    'contact.info.mobile.value': '+82-10-9161-0982',
    'contact.info.email.title': '이메일',
    'contact.info.email.value': 'bhkim@kieng.co.kr',
    'contact.info.email.desc': '24시간 접수 가능',
    'contact.info.address.title': '주소',
    'contact.info.address.value': '경기도 김포시 대곶면 대곶로 382번길 122',
    'contact.info.address.desc': '상세주소는 문의 시 안내',
    'contact.info.hours.title': '영업시간',
    'contact.info.hours.value': '월~금 09:00~18:00',
    'contact.info.hours.desc': '토요일 09:00~13:00',
    'contact.form.name.label': '이름 *',
    'contact.form.name.placeholder': '이름을 입력하세요',
    'contact.form.company.label': '회사명',
    'contact.form.company.placeholder': '회사명을 입력하세요',
    'contact.form.email.label': '이메일 *',
    'contact.form.email.placeholder': '이메일을 입력하세요',
    'contact.form.phone.label': '전화번호',
    'contact.form.phone.placeholder': '전화번호를 입력하세요',
    'contact.form.subject.label': '문의 제목 *',
    'contact.form.subject.placeholder': '문의 제목을 선택하세요',
    'contact.form.subject.product': '제품 문의',
    'contact.form.subject.service': '서비스 문의',
    'contact.form.subject.quote': '견적 문의',
    'contact.form.subject.support': '기술 지원',
    'contact.form.subject.other': '기타',
    'contact.form.message.label': '문의 내용 *',
    'contact.form.message.placeholder': '문의 내용을 상세히 입력해주세요',
    'contact.form.submitting': '전송 중...',
    'contact.form.success': '문의가 성공적으로 접수되었습니다. 빠른 시일 내에 연락드리겠습니다.',
    'contact.company.title': '회사 정보',
    'contact.company.name': '경인엔지니어링',
    'contact.company.desc': '여과 및 정화 설비 전문 기업',
    'contact.company.founded': '설립',
    'contact.company.founded.value': '2000년 (24년 경력)',
    'contact.company.business': '사업 분야',
    'contact.company.business.value': '필터, 저장탱크, 이온교환기, 환경설비',
    'contact.company.certification': '인증',
    'contact.company.certification.value': 'ISO 9001, 14001, 45001',
    'contact.departments.title': '부서별 연락처',
    'contact.departments.sales.name': '영업팀',
    'contact.departments.sales.desc': '제품 문의 및 견적',
    'contact.departments.tech.name': '기술팀',
    'contact.departments.tech.desc': '기술 지원 및 설계',
    'contact.departments.support.name': '고객지원팀',
    'contact.departments.support.desc': '유지보수 및 서비스',
    'contact.quick.title': '빠른 문의',
    'contact.quick.quote': '견적 요청',
    'contact.quick.services': '서비스 보기',
    'contact.quick.products': '제품 보기',
    'contact.quick.portfolio': '포트폴리오',
    'contact.location.title': '위치',
    'contact.location.desc': '경기도 김포시 대곶면 대곶로 382번길 122에 위치하고 있습니다',
    'contact.location.map.placeholder': '지도가 여기에 표시됩니다',
    'contact.faq.title': '자주 묻는 질문',
    'contact.faq.subtitle': '고객님들이 자주 문의하시는 내용입니다',
    'contact.faq.quote.question': '견적은 얼마나 걸리나요?',
    'contact.faq.quote.answer': '일반적으로 문의 후 1-2일 내에 견적을 제공해드립니다. 복잡한 프로젝트의 경우 추가 시간이 필요할 수 있습니다.',
    'contact.faq.installation.question': '설치 서비스를 제공하나요?',
    'contact.faq.installation.answer': '네, 모든 제품에 대해 현장 설치, 시운전, 운전 교육까지 원스톱 서비스를 제공합니다.',
    'contact.faq.maintenance.question': '유지보수는 어떻게 받을 수 있나요?',
    'contact.faq.maintenance.answer': '24/7 기술 지원 라인을 운영하고 있으며, 정기 유지보수 서비스도 제공합니다.',
    'contact.faq.overseas.question': '해외 프로젝트도 수행하나요?',
    'contact.faq.overseas.answer': '네, 동남아시아, 중동, 아프리카 등 다양한 해외 프로젝트를 수행하고 있습니다.',
    
    // Footer
    'footer.company.desc': '2000년 설립 이래 필터, 저장탱크, 이온교환기 등 여과 및 정화 설비 전문 제조업체로 현대엔지니어링, 포스코, 삼성물산 등 주요 기업의 신뢰받는 파트너입니다.',
    'footer.quickLinks': '빠른 링크',
    'footer.services': '주요 서비스',
    'footer.social.desc': '최신 소식과 기술 정보를 받아보세요',
    'footer.privacy': '개인정보처리방침',
    'footer.terms': '이용약관',
    'footer.sitemap': '사이트맵',
    'footer.copyright': '경인엔지니어링. All rights reserved.',
    'footer.company.name': '경인엔지니어링',
    'footer.projects': '프로젝트',
    'footer.phone': '031-987-6127',
    'footer.email': 'bhkim@kieng.co.kr',
    'footer.address': '경기도 김포시 대곶면 대곶로 382번길 122',
    
    // Quote Page
    'quote.badge': '견적 문의',
    'quote.title': '견적 요청',
    'quote.description': '24년간 축적된 기술력으로 최적의 견적을 제공합니다. 상세한 요구사항을 알려주시면 정확한 견적을 드립니다.',
    'quote.process.title': '견적 프로세스',
    'quote.process.subtitle': '간단한 4단계로 정확한 견적을 받아보세요',
    'quote.process.request.title': '견적 요청',
    'quote.process.request.desc': '제품 사양과 수량을 상세히 입력해주세요',
    'quote.process.review.title': '기술 검토',
    'quote.process.review.desc': '전문 엔지니어가 요구사항을 검토합니다',
    'quote.process.send.title': '견적서 발송',
    'quote.process.send.desc': '1-2일 내에 상세 견적서를 제공합니다',
    'quote.process.contract.title': '계약 및 제작',
    'quote.process.contract.desc': '계약 후 전문 기술로 제작합니다',
    'quote.form.title': '견적 요청서',
    'quote.form.name': '이름',
    'quote.form.name.placeholder': '이름을 입력하세요',
    'quote.form.company': '회사명',
    'quote.form.company.placeholder': '회사명을 입력하세요',
    'quote.form.email': '이메일',
    'quote.form.email.placeholder': '이메일을 입력하세요',
    'quote.form.phone': '전화번호',
    'quote.form.phone.placeholder': '전화번호를 입력하세요',
    'quote.form.productType': '제품 유형',
    'quote.form.productType.placeholder': '제품 유형을 선택하세요',
    'quote.form.quantity': '수량',
    'quote.form.quantity.placeholder': '예: 1대, 10개, 1세트',
    'quote.form.specifications': '제품 사양',
    'quote.form.specifications.placeholder': '제품의 상세 사양을 입력해주세요 (크기, 재질, 압력, 온도 등)',
    'quote.form.deadline': '납기 희망일',
    'quote.form.budget': '예산 범위',
    'quote.form.budget.placeholder': '예산 범위를 선택하세요',
    'quote.form.additionalInfo': '추가 요구사항',
    'quote.form.additionalInfo.placeholder': '특별한 요구사항이나 추가 문의사항이 있으시면 입력해주세요',
    'quote.form.submit': '견적 요청하기',
    'quote.form.submitting': '견적 요청 중...',
    'quote.success.message': '견적 요청이 성공적으로 접수되었습니다. 1-2일 내에 상세 견적서를 이메일로 발송해드리겠습니다.',
    'quote.error.message': '견적 요청 전송에 실패했습니다. 다시 시도해주세요.',
    'quote.why.title': '경인엔지니어링을 선택하는 이유',
    'quote.why.subtitle': '24년간 축적된 기술력과 경험으로 최적의 솔루션을 제공합니다',
    'quote.why.experience.title': '24년 경력',
    'quote.why.experience.desc': '2000년 설립 이후 지속적인 기술 개발과 프로젝트 수행으로 축적된 풍부한 경험',
    'quote.why.custom.title': '맞춤 설계',
    'quote.why.custom.desc': '고객의 요구사항에 맞는 맞춤형 설계 및 제작으로 최적의 성능 제공',
    'quote.why.partnership.title': '글로벌 파트너십',
    'quote.why.partnership.desc': 'Purolite, Calgon 등 글로벌 파트너사와의 협력을 통한 최고 품질의 제품 제공',
    'quote.why.onestop.title': '원스톱 서비스',
    'quote.why.onestop.desc': '설계부터 제작, 설치, 시운전까지 모든 과정을 책임지는 원스톱 서비스',
    'quote.why.quality.title': '품질 인증',
    'quote.why.quality.desc': 'ISO 9001, 14001, 45001 인증을 통한 체계적인 품질 관리 시스템',
    'quote.why.support.title': '24/7 지원',
    'quote.why.support.desc': '언제든지 문의 가능한 기술 지원 및 유지보수 서비스 제공',
    'quote.contact.title': '견적 문의 연락처',
    'quote.contact.subtitle': '견적 관련 문의는 아래 연락처로 언제든지 연락주세요',
    'quote.contact.phone.title': '전화 문의',
    'quote.contact.phone.desc': '영업팀 (평일 09:00~18:00)',
    'quote.contact.email.title': '이메일 문의',
    'quote.contact.email.desc': '24시간 접수 가능',
    'quote.contact.tech.title': '기술 상담',
    'quote.contact.tech.desc': '기술팀 (상세 사양 상담)',
    'quote.productTypes.filter': 'Filter & Coalescer',
    'quote.productTypes.filtration': 'Filtration Packages',
    'quote.productTypes.silencer': 'Silencer (with Vent Stack)',
    'quote.productTypes.storage': 'Storage Tank',
    'quote.productTypes.piping': 'Piping Spool & Package',
    'quote.productTypes.carbonCanister': 'Activated Carbon Canister',
    'quote.productTypes.carbonFilter': 'Activated Carbon Filter',
    'quote.productTypes.ionExchanger': 'Ion Exchanger',
    'quote.productTypes.custom': '맞춤 제작',
    'quote.productTypes.other': '기타',
    'quote.budgetRanges.select': '예산 범위를 선택하세요',
    'quote.budgetRanges.under10m': '1천만원 미만',
    'quote.budgetRanges.10m50m': '1천만원 ~ 5천만원',
    'quote.budgetRanges.50m100m': '5천만원 ~ 1억원',
    'quote.budgetRanges.100m500m': '1억원 ~ 5억원',
    'quote.budgetRanges.over500m': '5억원 이상',
    'quote.budgetRanges.consultation': '상담 후 결정',
    
    // Products Page
    'products.badge': '제품',
    'products.hero.title': '전문 여과 및 정화 제품',
    'products.hero.subtitle': '24년간 축적된 기술력으로 개발된 고품질 제품들을 확인하세요.',
    'products.categories.all': '전체',
    'products.categories.filter': '필터 시스템',
    'products.categories.tank': '저장 탱크',
    'products.categories.ion': '이온교환',
    'products.categories.env': '환경설비',
    'products.features.title': '주요 특징',
    'products.applications.title': '적용 분야',
    'products.specifications.title': '기술 사양',
    'products.allFeatures.title': '전체 특징',
    'products.allApplications.title': '전체 적용 분야',
    'products.expand': '자세히 보기',
    'products.collapse': '접기',
    'products.quote': '견적 문의',
    'products.viewServices': '서비스 보기',
    'products.cta.title': '맞춤형 제품이 필요하신가요?',
    'products.cta.subtitle': '고객의 요구사항에 맞는 최적의 제품을 설계하고 제조해드립니다.',
    'products.cta.contact': '문의하기',
    'products.cta.services': '서비스 보기',
    'products.special.design': '직접 설계 및 인허가',
    'products.special.custom': '맞춤형 설계',
    
    // Product Names
    'products.filter.coalescer.name': 'Filter & Coalescer',
    'products.filtration.packages.name': 'Filtration Packages',
    'products.silencer.name': 'Silencer (with Vent Stack)',
    'products.storage.tank.name': 'Storage Tank',
    'products.piping.spool.name': 'Piping Spool & Package',
    'products.activated.carbon.canister.name': 'Activated Carbon Canister',
    'products.activated.carbon.filter.name': 'Activated Carbon Filter',
    'products.ion.exchanger.name': 'Ion Exchanger',
    
    // Product Descriptions
    'products.filter.coalescer.desc': '고효율 여과 및 분리 시스템',
    'products.filtration.packages.desc': '맞춤형 여과 패키지 시스템',
    'products.silencer.desc': '소음 제거 및 환경 보호 시스템',
    'products.storage.tank.desc': '대용량 저장 탱크 시스템',
    'products.piping.spool.desc': '배관 시스템 및 패키지',
    'products.activated.carbon.canister.desc': '활성탄 정화 시스템',
    'products.activated.carbon.filter.desc': '활성탄 여과 시스템',
    'products.ion.exchanger.desc': '이온교환 수처리 시스템',
    
    // Product Features
    'products.filter.coalescer.feature1': 'Bag Filter System',
    'products.filter.coalescer.feature2': 'Activated Carbon Filter',
    'products.filter.coalescer.feature3': 'Coalescer Filter',
    'products.filter.coalescer.feature4': 'Custom Design & Engineering',
    'products.filter.coalescer.feature5': 'High Efficiency Filtration',
    'products.filter.coalescer.feature6': 'Automated Control System',
    
    'products.filtration.packages.feature1': 'Multi-stage Filtration',
    'products.filtration.packages.feature2': 'Automated Control',
    'products.filtration.packages.feature3': 'Pressure Monitoring',
    'products.filtration.packages.feature4': 'Filter Life Management',
    'products.filtration.packages.feature5': 'Easy Maintenance',
    'products.filtration.packages.feature6': 'Custom Engineering',
    
    'products.silencer.feature1': '20~40 dB(A) 소음 감소',
    'products.silencer.feature2': '배출가스 처리',
    'products.silencer.feature3': '내식성 재질',
    'products.silencer.feature4': '환경 규제 준수',
    'products.silencer.feature5': '정기 점검 시스템',
    'products.silencer.feature6': '맞춤형 설계',
    
    'products.storage.tank.feature1': '1~1000 m³ 용량 지원',
    'products.storage.tank.feature2': '화학 저항성 코팅',
    'products.storage.tank.feature3': '레벨 제어 시스템',
    'products.storage.tank.feature4': '안전 릴리프 밸브',
    'products.storage.tank.feature5': 'X-Ray 검사',
    'products.storage.tank.feature6': '초음파 검사',
    
    'products.piping.spool.feature1': '맞춤형 배관 설계',
    'products.piping.spool.feature2': '고품질 용접',
    'products.piping.spool.feature3': '압력 시험',
    'products.piping.spool.feature4': '품질 검사',
    'products.piping.spool.feature5': '현장 설치',
    'products.piping.spool.feature6': '시운전 지원',
    
    'products.activated.carbon.canister.feature1': '고품질 활성탄',
    'products.activated.carbon.canister.feature2': '효율적인 흡착',
    'products.activated.carbon.canister.feature3': '자동 제어',
    'products.activated.carbon.canister.feature4': '정기 교체',
    'products.activated.carbon.canister.feature5': '환경 친화적',
    'products.activated.carbon.canister.feature6': '맞춤형 설계',
    
    'products.activated.carbon.filter.feature1': '고효율 여과',
    'products.activated.carbon.filter.feature2': '활성탄 흡착',
    'products.activated.carbon.filter.feature3': '자동 제어',
    'products.activated.carbon.filter.feature4': '정기 교체',
    'products.activated.carbon.filter.feature5': '환경 친화적',
    'products.activated.carbon.filter.feature6': '맞춤형 설계',
    
    'products.ion.exchanger.feature1': 'Purolite 수지 사용',
    'products.ion.exchanger.feature2': '자동 재생 시스템',
    'products.ion.exchanger.feature3': 'PLC 제어',
    'products.ion.exchanger.feature4': 'HSE 인증',
    'products.ion.exchanger.feature5': '고품질 정수',
    'products.ion.exchanger.feature6': '맞춤형 설계',
    
    // Product Specifications
    'products.spec.capacity': '처리 용량',
    'products.spec.pressure': '압력 범위',
    'products.spec.temperature': '온도 범위',
    'products.spec.filtration': '여과 정밀도',
    'products.spec.material': '재질',
    'products.spec.certification': '인증',
    'products.spec.control': '제어',
    'products.spec.noise': '소음 감소',
    'products.spec.environment': '환경 규제',
    'products.spec.maintenance': '유지보수',
    'products.spec.volume': '용량',
    'products.spec.pressure.rating': '압력 등급',
    'products.spec.thickness': '두께',
    'products.spec.welding': '용접',
    'products.spec.pipe.size': '배관 크기',
    'products.spec.adsorption': '흡착 효율',
    'products.spec.carbon': '활성탄',
    'products.spec.regeneration': '재생 주기',
    'products.spec.water.quality': '수질 개선',
    
    // Product Applications
    'products.app.petrochemical': '석유화학 산업',
    'products.app.pharmaceutical': '제약 산업',
    'products.app.food': '식품 산업',
    'products.app.semiconductor': '반도체 산업',
    'products.app.power': '발전소',
    'products.app.water': '수처리 시설',
    'products.app.chemical': '화학 공정',
    'products.app.gas': '가스 처리',
    'products.app.liquid': '액체 정제',
    'products.app.industrial': '산업용 필터링',
    'products.app.chemical.storage': '화학 물질 저장',
    'products.app.crude.oil': '원유 저장',
    'products.app.gas.storage': '가스 저장',
    'products.app.industrial.storage': '산업용 저장',
    'products.app.oil.gas': '석유 가스',
    'products.app.industrial.piping': '산업용 배관',
    'products.app.gas.purification': '가스 정화',
    'products.app.odor': '냄새 제거',
    'products.app.voc': 'VOC 처리',
    'products.app.environmental': '환경 보호',
    'products.app.air': '공기 정화',
    'products.app.boiler': '보일러 급수',
    'products.app.cooling': '냉각수 처리',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    'nav.quote': 'Get Quote',
    'nav.tagline': 'Reliable Filtration & Purification Solutions',
    
    // Hero Section
    'hero.badge': 'Innovative Engineering Solutions',
    'hero.title1': 'Reliable',
    'hero.title2': 'Filtration & Purification Solutions',
    'hero.description': 'Since 2000, we have been manufacturing high-quality filtration and purification equipment including filters, storage tanks, and ion exchangers, partnering with major companies like Hyundai Engineering, POSCO, and Samsung C&T.',
    'hero.contact': 'Project Inquiry',
    'hero.video': 'Company Video',
    'hero.stats.experience': 'Years Experience',
    'hero.stats.factory': '㎡ Factory Size',
    'hero.stats.iso': 'Certification System',
    'hero.feature.iso': 'ISO 9001 Certified',
    'hero.feature.iso.desc': 'Quality Management',
    'hero.feature.support': '24/7 Support',
    'hero.feature.support.desc': 'Technical Support',
    'hero.feature.custom': 'Custom Design',
    'hero.feature.custom.desc': 'Solution Provider',
    
    // Services Section (Legacy - keeping for compatibility)
    'services.title': 'Professional Filtration & Purification Solutions',
    'services.subtitle': 'We provide one-stop services from design to manufacturing and installation of various purification equipment including filters, storage tanks, and ion exchangers.',
    'services.filter.title': 'Filter & Coalescer',
    'services.filter.desc': 'Filter, Coalescer and Filteration Package',
    'services.tank.title': 'Storage Tank & Piping',
    'services.tank.desc': 'Storage Tank, Piping Spool and Package',
    'services.ion.title': 'Ion Exchange System',
    'services.ion.desc': 'Ion Exchanger and Water Treatment Solutions',
    'services.env.title': 'Environmental Solutions',
    'services.env.desc': 'Silencer, Activated Carbon Canister',
    'services.details': 'Learn More',
    'services.cta.title': 'Need Custom Solutions?',
    'services.cta.desc': 'Our expert team will propose the optimal solution tailored to your specific requirements.',
    'services.cta.consult': 'Free Consultation',
    'services.cta.portfolio': 'View Portfolio',
    
    // Portfolio Section
    'portfolio.badge': 'Portfolio',
    'portfolio.title': 'Project Achievements',
    'portfolio.subtitle': 'Check out our diverse projects and achievements over 24 years',
    'portfolio.projects.title': 'Main Projects',
    'portfolio.projects.subtitle': 'Cooperative projects with major companies like Hyundai Engineering, POSCO, and Samsung C&T',
    'portfolio.gallery.title': 'Work Site Gallery',
    'portfolio.gallery.subtitle': 'Check out the installation and construction process',
    'portfolio.filter.all': 'All',
    'portfolio.filter.filter': 'Filter System',
    'portfolio.filter.tank': 'Storage Tank',
    'portfolio.filter.ion': 'Ion Exchange',
    'portfolio.filter.env': 'Environmental Equipment',
    'portfolio.project.view': 'Learn More',
    'portfolio.project.client': 'Client',
    'portfolio.project.period': 'Period',
    'portfolio.project.description': 'Project Overview',
    'portfolio.project.achievements': 'Key Achievements',
    'portfolio.back': 'Back to List',
    'portfolio.stats.experience': 'Years Experience',
    'portfolio.stats.projects': 'Completed Projects',
    'portfolio.stats.international': 'International Projects',
    'portfolio.stats.clients': 'Major Clients',
    
    // About Section
    'about.badge': 'About Us',
    'about.title1': '24 Years of Trusted',
    'about.title2': 'Filtration & Purification Specialist',
    'about.description': 'Since its establishment in 2000, Kyoungin Engineering has grown as a specialized manufacturer of filtration and purification equipment including filters, storage tanks, and ion exchangers, building partnerships with major companies such as Hyundai Engineering, POSCO E&C, and Samsung C&T.',
    'about.partnership.title': 'Global Partnership',
    'about.partnership.desc': 'Official distributor of Purolite(UK) ion exchange resins and Calgon(USA) activated carbon',
    'about.certification.title': 'Certification System',
    'about.certification.desc': 'ISO 9001, 14001, 45001 Quality/Environmental/Occupational Health & Safety Management System',
    'about.quality.title': 'Reliable Quality',
    'about.quality.desc': 'ASME U Stamp certification in progress, systematic quality management system',
    'about.history': 'Company History',
    'about.certificates': 'View Certificates',
    'about.numbers.title': 'Kyoungin Engineering by Numbers',
    'about.numbers.desc': 'Check our reliable track record and achievements',
    'about.stats.experience': 'Years Experience',
    'about.stats.factory': '㎡ Factory Size',
    'about.stats.iso': 'ISO Certifications',
    'about.stats.newFactory': 'Gimpo New Factory',
    
    // About Page Additional Keys
    'about.values.title': 'Management Philosophy',
    'about.values.subtitle': 'Values and philosophy pursued by Kyoungin Engineering',
    'about.values.customer.title': 'Customer Satisfaction',
    'about.values.customer.desc': 'We prioritize customer requirements and provide the highest quality and service.',
    'about.values.innovation.title': 'Technology Innovation',
    'about.values.innovation.desc': 'We contribute to industrial development through continuous technology development and innovation.',
    'about.values.social.title': 'Social Responsibility',
    'about.values.social.desc': 'We practice sustainable management that contributes to environmental protection and social development.',
    'about.values.talent.title': 'Talent Development',
    'about.values.talent.desc': 'We cultivate excellent talent and support the growth and development of our members.',
    'about.history.title': 'Company History',
    'about.history.subtitle': '24 years of growth process and major milestones',
    'about.history.2000.title': 'Company Establishment',
    'about.history.2000.desc': 'Establishment of Kyoungin Engineering, start of filtration and purification equipment manufacturing',
    'about.history.2005.title': 'ISO 9001 Certification',
    'about.history.2005.desc': 'Quality management system certification obtained',
    'about.history.2010.title': 'Overseas Expansion',
    'about.history.2010.desc': 'Entry into Southeast Asian market, first overseas project execution',
    'about.history.2015.title': 'ISO 14001 Certification',
    'about.history.2015.desc': 'Environmental management system certification obtained',
    'about.history.2020.title': 'ISO 45001 Certification',
    'about.history.2020.desc': 'Occupational health and safety management system certification obtained',
    'about.history.2024.title': '24th Anniversary',
    'about.history.2024.desc': 'Growth with 24 years of accumulated technology and experience',
    'about.certifications.title': 'Certifications & Registrations',
    'about.certifications.subtitle': 'Quality management system and factory registration complying with international standards',
    'about.certifications.iso9001.title': 'ISO 9001',
    'about.certifications.iso9001.desc': 'Quality Management System',
    'about.certifications.iso9001.year': 'Obtained in 2005',
    'about.certifications.iso14001.title': 'ISO 14001',
    'about.certifications.iso14001.desc': 'Environmental Management System',
    'about.certifications.iso14001.year': 'Obtained in 2015',
    'about.certifications.iso45001.title': 'ISO 45001',
    'about.certifications.iso45001.desc': 'Occupational Health & Safety Management System',
    'about.certifications.iso45001.year': 'Obtained in 2020',
    'about.certifications.factory.title': 'Factory Registration',
    'about.certifications.factory.desc': 'Manufacturing Registration',
    'about.certifications.factory.year': 'Official Registration',
    'about.certifications.meaning.title': 'Meaning of Certifications',
    'about.certifications.quality.title': 'Quality Assurance',
    'about.certifications.quality.desc': 'We provide the highest quality products through systematic quality management system with ISO 9001 certification.',
    'about.certifications.environment.title': 'Environmental Friendly',
    'about.certifications.environment.desc': 'We practice sustainable management prioritizing environmental protection with ISO 14001 certification.',
    'about.certifications.safety.title': 'Safety & Health',
    'about.certifications.safety.desc': 'We protect the safety and health of employees and customers as top priority with ISO 45001 certification.',
    'about.partnerships.title': 'Global Partnerships',
    'about.partnerships.subtitle': 'Cooperation with world-class partners',
    'about.partnerships.purolite.title': 'Purolite (UK)',
    'about.partnerships.purolite.desc': 'Official distributor of ion exchange resins providing high-quality water treatment solutions.',
    'about.partnerships.purolite.item1': 'High-quality ion exchange resins',
    'about.partnerships.purolite.item2': 'Technical support and training',
    'about.partnerships.purolite.item3': 'Customized solution provision',
    'about.partnerships.calgon.title': 'Calgon (USA)',
    'about.partnerships.calgon.desc': 'Official distributor of activated carbon providing environmentally friendly purification solutions.',
    'about.partnerships.calgon.item1': 'High-quality activated carbon',
    'about.partnerships.calgon.item2': 'Environmental purification solutions',
    'about.partnerships.calgon.item3': 'Sustainable technology',
    'about.cta.title': 'Looking for partners to grow together',
    'about.cta.subtitle': 'We support your project success with 24 years of accumulated technology and experience.',
    'about.cta.contact': 'Contact Us',
    'about.cta.services': 'View Services',
    'about.stats.projects': 'Completed Projects',
    'about.stats.international': 'International Projects',
    'about.stats.clients': 'Major Clients',
    
    // Contact Section
    'contact.badge': 'Contact',
    'contact.title': 'Project Consultation & Inquiry',
    'contact.subtitle': 'Consult directly with experts and receive customized solutions. We do our best to provide quick responses.',
    'contact.form.title': 'Request Quote',
    'contact.form.name': 'Name',
    'contact.form.phone': 'Phone',
    'contact.form.email': 'Email',
    'contact.form.company': 'Company',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Inquiry',
    'contact.info.title': 'Contact Information',
    'contact.info.desc': 'Feel free to contact us anytime. Our professional consultation team will respond promptly.',
    'contact.phone': 'Phone Number',
    'contact.email': 'Email',
    'contact.address': 'Factory Address',
    'contact.size': 'Factory Size',
    'contact.map.title': 'Directions',
    'contact.map.desc': 'Click on view map to check the detailed location.',
    'contact.map.view': 'View Map →',
    
    // Contact Page
    'contact.page.badge': 'Contact',
    'contact.page.title': 'Inquiry & Contact',
    'contact.page.subtitle': 'We provide optimal solutions tailored to customer requirements with 24 years of accumulated technology and experience.',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.value': '031-987-6127',
    'contact.info.phone.desc': 'Mon-Fri 09:00~18:00',
    'contact.info.fax.title': 'Fax',
    'contact.info.fax.value': '031-988-6128',
    'contact.info.contactPerson.title': 'Contact Person',
    'contact.info.contactPerson.value': 'Technical Sales Team Manager Mac Kim',
    'contact.info.mobile.title': 'Mobile',
    'contact.info.mobile.value': '+82-10-9161-0982',
    'contact.info.email.title': 'Email',
    'contact.info.email.value': 'bhkim@kieng.co.kr',
    'contact.info.email.desc': 'Available 24/7',
    'contact.info.address.title': 'Address',
    'contact.info.address.value': '122, Daegot-ro 382beon-gil, Daegot-myeon, Gimpo-si, Gyeonggi-do',
    'contact.info.address.desc': 'Detailed address provided upon inquiry',
    'contact.info.hours.title': 'Business Hours',
    'contact.info.hours.value': 'Mon-Fri 09:00~18:00',
    'contact.info.hours.desc': 'Sat 09:00~13:00',
    'contact.form.name.label': 'Name *',
    'contact.form.name.placeholder': 'Enter your name',
    'contact.form.company.label': 'Company',
    'contact.form.company.placeholder': 'Enter company name',
    'contact.form.email.label': 'Email *',
    'contact.form.email.placeholder': 'Enter your email',
    'contact.form.phone.label': 'Phone',
    'contact.form.phone.placeholder': 'Enter your phone number',
    'contact.form.subject.label': 'Inquiry Subject *',
    'contact.form.subject.placeholder': 'Select inquiry subject',
    'contact.form.subject.product': 'Product Inquiry',
    'contact.form.subject.service': 'Service Inquiry',
    'contact.form.subject.quote': 'Quote Inquiry',
    'contact.form.subject.support': 'Technical Support',
    'contact.form.subject.other': 'Other',
    'contact.form.message.label': 'Inquiry Content *',
    'contact.form.message.placeholder': 'Please enter detailed inquiry content',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Your inquiry has been successfully received. We will contact you soon.',
    'contact.company.title': 'Company Information',
    'contact.company.name': 'Kyoungin Engineering',
    'contact.company.desc': 'Specialized in filtration and purification equipment',
    'contact.company.founded': 'Established',
    'contact.company.founded.value': '2000 (24 years of experience)',
    'contact.company.business': 'Business Areas',
    'contact.company.business.value': 'Filters, Storage Tanks, Ion Exchangers, Environmental Equipment',
    'contact.company.certification': 'Certifications',
    'contact.company.certification.value': 'ISO 9001, 14001, 45001',
    'contact.departments.title': 'Department Contacts',
    'contact.departments.sales.name': 'Sales Team',
    'contact.departments.sales.desc': 'Product inquiries and quotes',
    'contact.departments.tech.name': 'Technical Team',
    'contact.departments.tech.desc': 'Technical support and design',
    'contact.departments.support.name': 'Customer Support Team',
    'contact.departments.support.desc': 'Maintenance and service',
    'contact.quick.title': 'Quick Inquiry',
    'contact.quick.quote': 'Request Quote',
    'contact.quick.services': 'View Services',
    'contact.quick.products': 'View Products',
    'contact.quick.portfolio': 'Portfolio',
    'contact.location.title': 'Location',
    'contact.location.desc': 'Located at 122, Daegot-ro 382beon-gil, Daegot-myeon, Gimpo-si, Gyeonggi-do',
    'contact.location.map.placeholder': 'Map will be displayed here',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Common inquiries from customers',
    'contact.faq.quote.question': 'How long does it take to get a quote?',
    'contact.faq.quote.answer': 'We typically provide quotes within 1-2 days of inquiry. Additional time may be required for complex projects.',
    'contact.faq.installation.question': 'Do you provide installation services?',
    'contact.faq.installation.answer': 'Yes, we provide one-stop services including on-site installation, commissioning, and operation training for all products.',
    'contact.faq.maintenance.question': 'How can I receive maintenance services?',
    'contact.faq.maintenance.answer': 'We operate a 24/7 technical support line and also provide regular maintenance services.',
    'contact.faq.overseas.question': 'Do you perform overseas projects?',
    'contact.faq.overseas.answer': 'Yes, we perform various overseas projects in Southeast Asia, Middle East, Africa, and other regions.',
    
    // Quote Page
    'quote.badge': 'Quote Inquiry',
    'quote.title': 'Request Quote',
    'quote.description': 'We provide optimal quotes with 24 years of accumulated technology. Please provide detailed requirements for accurate quotes.',
    'quote.process.title': 'Quote Process',
    'quote.process.subtitle': 'Get accurate quotes in 4 simple steps',
    'quote.process.request.title': 'Quote Request',
    'quote.process.request.desc': 'Please enter detailed product specifications and quantity',
    'quote.process.review.title': 'Technical Review',
    'quote.process.review.desc': 'Professional engineers review requirements',
    'quote.process.send.title': 'Quote Submission',
    'quote.process.send.desc': 'Provide detailed quotes within 1-2 days',
    'quote.process.contract.title': 'Contract & Manufacturing',
    'quote.process.contract.desc': 'Manufacture with professional technology after contract',
    'quote.form.title': 'Quote Request Form',
    'quote.form.name': 'Name',
    'quote.form.name.placeholder': 'Enter your name',
    'quote.form.company': 'Company',
    'quote.form.company.placeholder': 'Enter company name',
    'quote.form.email': 'Email',
    'quote.form.email.placeholder': 'Enter your email',
    'quote.form.phone': 'Phone',
    'quote.form.phone.placeholder': 'Enter your phone number',
    'quote.form.productType': 'Product Type',
    'quote.form.productType.placeholder': 'Select product type',
    'quote.form.quantity': 'Quantity',
    'quote.form.quantity.placeholder': 'e.g., 1 unit, 10 pcs, 1 set',
    'quote.form.specifications': 'Product Specifications',
    'quote.form.specifications.placeholder': 'Enter detailed product specifications (size, material, pressure, temperature, etc.)',
    'quote.form.deadline': 'Delivery Date',
    'quote.form.budget': 'Budget Range',
    'quote.form.budget.placeholder': 'Select budget range',
    'quote.form.additionalInfo': 'Additional Requirements',
    'quote.form.additionalInfo.placeholder': 'Enter special requirements or additional inquiries',
    'quote.form.submit': 'Request Quote',
    'quote.form.submitting': 'Submitting quote request...',
    'quote.success.message': 'Quote request has been successfully submitted. We will send a detailed quote via email within 1-2 days.',
    'quote.error.message': 'Quote request submission failed. Please try again.',
    'quote.why.title': 'Why Choose Kyoungin Engineering',
    'quote.why.subtitle': 'We provide optimal solutions with 24 years of accumulated technology and experience',
    'quote.why.experience.title': '24 Years Experience',
    'quote.why.experience.desc': 'Rich experience accumulated through continuous technology development and project execution since establishment in 2000',
    'quote.why.custom.title': 'Custom Design',
    'quote.why.custom.desc': 'Custom design and manufacturing tailored to customer requirements for optimal performance',
    'quote.why.partnership.title': 'Global Partnership',
    'quote.why.partnership.desc': 'Highest quality products through collaboration with global partners like Purolite and Calgon',
    'quote.why.onestop.title': 'One-Stop Service',
    'quote.why.onestop.desc': 'One-stop service responsible for all processes from design to manufacturing, installation, and commissioning',
    'quote.why.quality.title': 'Quality Certification',
    'quote.why.quality.desc': 'Systematic quality management system through ISO 9001, 14001, 45001 certification',
    'quote.why.support.title': '24/7 Support',
    'quote.why.support.desc': 'Technical support and maintenance services available anytime',
    'quote.contact.title': 'Quote Inquiry Contact',
    'quote.contact.subtitle': 'Please contact us anytime for quote-related inquiries',
    'quote.contact.phone.title': 'Phone Inquiry',
    'quote.contact.phone.desc': 'Sales Team (Mon-Fri 09:00~18:00)',
    'quote.contact.email.title': 'Email Inquiry',
    'quote.contact.email.desc': 'Available 24/7',
    'quote.contact.tech.title': 'Technical Consultation',
    'quote.contact.tech.desc': 'Technical Team (Detailed specification consultation)',
    'quote.productTypes.filter': 'Filter & Coalescer',
    'quote.productTypes.filtration': 'Filtration Packages',
    'quote.productTypes.silencer': 'Silencer (with Vent Stack)',
    'quote.productTypes.storage': 'Storage Tank',
    'quote.productTypes.piping': 'Piping Spool & Package',
    'quote.productTypes.carbonCanister': 'Activated Carbon Canister',
    'quote.productTypes.carbonFilter': 'Activated Carbon Filter',
    'quote.productTypes.ionExchanger': 'Ion Exchanger',
    'quote.productTypes.custom': 'Custom Manufacturing',
    'quote.productTypes.other': 'Other',
    'quote.budgetRanges.select': 'Select budget range',
    'quote.budgetRanges.under10m': 'Under 10 million KRW',
    'quote.budgetRanges.10m50m': '10-50 million KRW',
    'quote.budgetRanges.50m100m': '50-100 million KRW',
    'quote.budgetRanges.100m500m': '100-500 million KRW',
    'quote.budgetRanges.over500m': 'Over 500 million KRW',
    'quote.budgetRanges.consultation': 'Decide after consultation',
    
    // Services Page
    'services.badge': 'Professional Services',
    'services.hero.title': 'Professional Filtration & Purification Solutions',
    'services.hero.subtitle': 'We provide optimal solutions tailored to customer requirements with 24 years of accumulated technology and experience.',
    'services.capacity.title': 'Annual Production Capacity',
    'services.capacity.subtitle': 'Filter & Coalescer, Filtration Packages, Silencer (with Vent Stack), Storage Tank, Piping Spool & Package, Activated Carbon Canister, Activated Carbon Filter, Ion Exchanger',
    'services.capacity.special': '⭐ Silencer and Filter can be designed and licensed directly',
    'services.capacity.table.description': 'DESCRIPTION',
    'services.capacity.table.unit': 'CAPACITY /UNIT',
    'services.capacity.table.year': 'CAPACITY /YEAR',
    'services.capacity.table.special': 'Special Capability',
    'services.capacity.stats.total': 'Total Annual Capacity (Ton)',
    'services.capacity.stats.products': 'Product Types',
    'services.capacity.stats.design': 'Direct Design & Licensing',
    'services.capacity.stats.unit': 'Unit Production Capacity (Ton)',
    'services.capacity.special.design': 'Direct Design & Licensing',
    'services.capacity.special.custom': 'Custom Design',
    'services.products.title': 'Product Details',
    'services.products.subtitle': 'Check technical specifications and features of each product',
    'services.products.filter.title': 'Filter & Coalescer',
    'services.products.filter.design': 'Direct Design & Licensing',
    'services.products.filter.desc': 'High-efficiency filtration system that removes impurities from liquids and separates emulsified water droplets. Used in various industrial fields, providing customized solutions optimized for customer requirements.',
    'services.products.filter.feature1': 'High-efficiency filtration and separation performance',
    'services.products.filter.feature2': 'Support for various materials and sizes',
    'services.products.filter.feature3': 'Automated control system',
    'services.products.filter.feature4': 'Easy maintenance and replacement',
    'services.products.filter.spec1': 'Processing Capacity',
    'services.products.filter.spec2': 'Pressure Range',
    'services.products.filter.spec3': 'Temperature Range',
    'services.products.filter.spec4': 'Filtration Precision',
    'services.products.filter.spec5': 'Material',
    'services.products.filter.spec6': 'Certification',
    'services.products.silencer.title': 'Silencer (with Vent Stack)',
    'services.products.silencer.design': 'Direct Design & Licensing',
    'services.products.silencer.desc': 'Noise reduction equipment that reduces exhaust gas noise and prevents environmental pollution. Used in various industrial facilities, providing efficient noise reduction while complying with environmental regulations.',
    'services.products.silencer.feature1': '20~40 dB(A) noise reduction',
    'services.products.silencer.feature2': 'Exhaust gas treatment function',
    'services.products.silencer.feature3': 'Corrosion-resistant materials',
    'services.products.silencer.feature4': 'Environmental regulation compliance',
    'services.products.silencer.spec1': 'Processing Capacity',
    'services.products.silencer.spec2': 'Noise Reduction',
    'services.products.silencer.spec3': 'Material',
    'services.products.silencer.spec4': 'Certification',
    'services.products.silencer.spec5': 'Environmental Regulations',
    'services.products.silencer.spec6': 'Maintenance',
    'services.products.tank.title': 'Storage Tank',
    'services.products.tank.design': 'Custom Design',
    'services.products.tank.desc': 'Large-capacity storage tanks for various liquids and gases. Provides customized design for safe storage of various materials including chemicals, crude oil, and gases.',
    'services.products.tank.feature1': '1~1000 m³ capacity support',
    'services.products.tank.feature2': 'Chemical-resistant coating',
    'services.products.tank.feature3': 'Level control system',
    'services.products.tank.feature4': 'Safety relief valve',
    'services.products.tank.spec1': 'Capacity',
    'services.products.tank.spec2': 'Pressure Rating',
    'services.products.tank.spec3': 'Material',
    'services.products.tank.spec4': 'Thickness',
    'services.products.tank.spec5': 'Certification',
    'services.products.tank.spec6': 'Welding',
    'services.products.ion.title': 'Ion Exchanger',
    'services.products.ion.design': 'Custom Design',
    'services.products.ion.desc': 'Water treatment equipment that removes hardness, silica, TDS, etc. from water using ion exchange resins. Provides high-quality water purification systems using Purolite resins.',
    'services.products.ion.feature1': 'Purolite resin usage',
    'services.products.ion.feature2': 'Automatic regeneration system',
    'services.products.ion.feature3': 'PLC control system',
    'services.products.ion.feature4': 'HSE certification',
    'services.products.ion.spec1': 'Processing Capacity',
    'services.products.ion.spec2': 'Water Quality Improvement',
    'services.products.ion.spec3': 'Regeneration Cycle',
    'services.products.ion.spec4': 'Material',
    'services.products.ion.spec5': 'Certification',
    'services.products.ion.spec6': 'Control',
    'services.products.desc.title': 'Product Description',
    'services.products.spec.title': 'Technical Specifications',
    'services.tabs.features': 'Key Features',
    'services.tabs.specifications': 'Technical Specifications',
    'services.tabs.process': 'Process',
    'services.tabs.cta.title': 'Need a Custom Solution?',
    'services.tabs.cta.desc': 'Our expert engineers will propose the optimal solution tailored to your requirements.',
    'services.tabs.cta.consult': 'Request Free Consultation',
    'services.tabs.cta.portfolio': 'View Portfolio',
    'services.faq.title': 'Frequently Asked Questions',
    'services.faq.subtitle': 'We have compiled the most frequently asked questions from our customers.',
    'services.faq.q1': 'How can I get a service quote?',
    'services.faq.a1': 'Click the "Get Quote" button on our homepage or contact us directly. Please provide detailed project requirements for an accurate quote.',
    'services.faq.q2': 'Do you provide installation and commissioning services?',
    'services.faq.a2': 'Yes, we provide one-stop services including on-site installation, commissioning, and operation training for all products. Our expert engineers provide direct support on-site.',
    'services.faq.q3': 'What is the warranty period?',
    'services.faq.a3': 'We provide 1-year warranty for standard products and 2-year warranty for custom products. Regular maintenance services are also provided.',
    'services.faq.q4': 'Do you perform overseas projects?',
    'services.faq.a4': 'Yes, we perform various overseas projects in Southeast Asia, Middle East, Africa, etc. We successfully complete projects in cooperation with local partners.',
    'services.faq.q5': 'How can I receive technical support?',
    'services.faq.a5': 'We operate a 24/7 technical support line. You can receive technical support anytime via phone, email, or remote access.',
    'services.contact.title': 'Project Inquiry',
    'services.contact.subtitle': 'Consult with our experts to find the optimal solution.',
    'services.contact.consult': 'Request Free Consultation',
    'services.contact.quote': 'Get Quote',
    
    // Footer
    'footer.company.desc': 'Since 2000, we have been a specialized manufacturer of filtration and purification equipment including filters, storage tanks, and ion exchangers, serving as a trusted partner for major companies like Hyundai Engineering, POSCO, and Samsung C&T.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Main Services',
    'footer.social.desc': 'Get the latest news and technical information',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.sitemap': 'Sitemap',
    'footer.copyright': 'Kyoungin Engineering Corp. All rights reserved.',
    'footer.company.name': 'Kyoungin Engineering',
    'footer.projects': 'Projects',
    'footer.phone': '031-987-6127',
    'footer.email': 'bhkim@kieng.co.kr',
    'footer.address': '122, Daegot-ro 382beon-gil, Daegot-myeon, Gimpo-si, Gyeonggi-do',
    
    // Products Page
    'products.badge': 'Products',
    'products.hero.title': 'Professional Filtration & Purification Products',
    'products.hero.subtitle': 'Check out our high-quality products developed with 24 years of accumulated technology.',
    'products.categories.all': 'All',
    'products.categories.filter': 'Filter System',
    'products.categories.tank': 'Storage Tank',
    'products.categories.ion': 'Ion Exchange',
    'products.categories.env': 'Environmental Equipment',
    'products.features.title': 'Key Features',
    'products.applications.title': 'Applications',
    'products.specifications.title': 'Technical Specifications',
    'products.allFeatures.title': 'All Features',
    'products.allApplications.title': 'All Applications',
    'products.expand': 'Learn More',
    'products.collapse': 'Collapse',
    'products.quote': 'Request Quote',
    'products.viewServices': 'View Services',
    'products.cta.title': 'Need Custom Products?',
    'products.cta.subtitle': 'We design and manufacture optimal products tailored to customer requirements.',
    'products.cta.contact': 'Contact Us',
    'products.cta.services': 'View Services',
    'products.special.design': 'Direct Design & Licensing',
    'products.special.custom': 'Custom Design',
    
    // Product Names
    'products.filter.coalescer.name': 'Filter & Coalescer',
    'products.filtration.packages.name': 'Filtration Packages',
    'products.silencer.name': 'Silencer (with Vent Stack)',
    'products.storage.tank.name': 'Storage Tank',
    'products.piping.spool.name': 'Piping Spool & Package',
    'products.activated.carbon.canister.name': 'Activated Carbon Canister',
    'products.activated.carbon.filter.name': 'Activated Carbon Filter',
    'products.ion.exchanger.name': 'Ion Exchanger',
    
    // Product Descriptions
    'products.filter.coalescer.desc': 'High-efficiency filtration and separation system',
    'products.filtration.packages.desc': 'Custom filtration package system',
    'products.silencer.desc': 'Noise reduction and environmental protection system',
    'products.storage.tank.desc': 'Large-capacity storage tank system',
    'products.piping.spool.desc': 'Piping system and package',
    'products.activated.carbon.canister.desc': 'Activated carbon purification system',
    'products.activated.carbon.filter.desc': 'Activated carbon filtration system',
    'products.ion.exchanger.desc': 'Ion exchange water treatment system',
    
    // Product Features
    'products.filter.coalescer.feature1': 'Bag Filter System',
    'products.filter.coalescer.feature2': 'Activated Carbon Filter',
    'products.filter.coalescer.feature3': 'Coalescer Filter',
    'products.filter.coalescer.feature4': 'Custom Design & Engineering',
    'products.filter.coalescer.feature5': 'High Efficiency Filtration',
    'products.filter.coalescer.feature6': 'Automated Control System',
    
    'products.filtration.packages.feature1': 'Multi-stage Filtration',
    'products.filtration.packages.feature2': 'Automated Control',
    'products.filtration.packages.feature3': 'Pressure Monitoring',
    'products.filtration.packages.feature4': 'Filter Life Management',
    'products.filtration.packages.feature5': 'Easy Maintenance',
    'products.filtration.packages.feature6': 'Custom Engineering',
    
    'products.silencer.feature1': '20~40 dB(A) noise reduction',
    'products.silencer.feature2': 'Exhaust gas treatment',
    'products.silencer.feature3': 'Corrosion-resistant materials',
    'products.silencer.feature4': 'Environmental regulation compliance',
    'products.silencer.feature5': 'Regular inspection system',
    'products.silencer.feature6': 'Custom design',
    
    'products.storage.tank.feature1': '1~1000 m³ capacity support',
    'products.storage.tank.feature2': 'Chemical-resistant coating',
    'products.storage.tank.feature3': 'Level control system',
    'products.storage.tank.feature4': 'Safety relief valve',
    'products.storage.tank.feature5': 'X-Ray inspection',
    'products.storage.tank.feature6': 'Ultrasonic inspection',
    
    'products.piping.spool.feature1': 'Custom piping design',
    'products.piping.spool.feature2': 'High-quality welding',
    'products.piping.spool.feature3': 'Pressure testing',
    'products.piping.spool.feature4': 'Quality inspection',
    'products.piping.spool.feature5': 'On-site installation',
    'products.piping.spool.feature6': 'Commissioning support',
    
    'products.activated.carbon.canister.feature1': 'High-quality activated carbon',
    'products.activated.carbon.canister.feature2': 'Efficient adsorption',
    'products.activated.carbon.canister.feature3': 'Automatic control',
    'products.activated.carbon.canister.feature4': 'Regular replacement',
    'products.activated.carbon.canister.feature5': 'Environmentally friendly',
    'products.activated.carbon.canister.feature6': 'Custom design',
    
    'products.activated.carbon.filter.feature1': 'High-efficiency filtration',
    'products.activated.carbon.filter.feature2': 'Activated carbon adsorption',
    'products.activated.carbon.filter.feature3': 'Automatic control',
    'products.activated.carbon.filter.feature4': 'Regular replacement',
    'products.activated.carbon.filter.feature5': 'Environmentally friendly',
    'products.activated.carbon.filter.feature6': 'Custom design',
    
    'products.ion.exchanger.feature1': 'Purolite resin usage',
    'products.ion.exchanger.feature2': 'Automatic regeneration system',
    'products.ion.exchanger.feature3': 'PLC control',
    'products.ion.exchanger.feature4': 'HSE certification',
    'products.ion.exchanger.feature5': 'High-quality water purification',
    'products.ion.exchanger.feature6': 'Custom design',
    
    // Product Specifications
    'products.spec.capacity': 'Processing Capacity',
    'products.spec.pressure': 'Pressure Range',
    'products.spec.temperature': 'Temperature Range',
    'products.spec.filtration': 'Filtration Precision',
    'products.spec.material': 'Material',
    'products.spec.certification': 'Certification',
    'products.spec.control': 'Control',
    'products.spec.noise': 'Noise Reduction',
    'products.spec.environment': 'Environmental Regulations',
    'products.spec.maintenance': 'Maintenance',
    'products.spec.volume': 'Capacity',
    'products.spec.pressure.rating': 'Pressure Rating',
    'products.spec.thickness': 'Thickness',
    'products.spec.welding': 'Welding',
    'products.spec.pipe.size': 'Pipe Size',
    'products.spec.adsorption': 'Adsorption Efficiency',
    'products.spec.carbon': 'Activated Carbon',
    'products.spec.regeneration': 'Regeneration Cycle',
    'products.spec.water.quality': 'Water Quality Improvement',
    
    // Product Applications
    'products.app.petrochemical': 'Petrochemical Industry',
    'products.app.pharmaceutical': 'Pharmaceutical Industry',
    'products.app.food': 'Food Industry',
    'products.app.semiconductor': 'Semiconductor Industry',
    'products.app.power': 'Power Plants',
    'products.app.water': 'Water Treatment Facilities',
    'products.app.chemical': 'Chemical Processes',
    'products.app.gas': 'Gas Treatment',
    'products.app.liquid': 'Liquid Purification',
    'products.app.industrial': 'Industrial Filtering',
    'products.app.chemical.storage': 'Chemical Storage',
    'products.app.crude.oil': 'Crude Oil Storage',
    'products.app.gas.storage': 'Gas Storage',
    'products.app.industrial.storage': 'Industrial Storage',
    'products.app.oil.gas': 'Oil & Gas',
    'products.app.industrial.piping': 'Industrial Piping',
    'products.app.gas.purification': 'Gas Purification',
    'products.app.odor': 'Odor Removal',
    'products.app.voc': 'VOC Treatment',
    'products.app.environmental': 'Environmental Protection',
    'products.app.air': 'Air Purification',
    'products.app.boiler': 'Boiler Feed Water',
    'products.app.cooling': 'Cooling Water Treatment',
    
    // Portfolio Page - Gallery Filters and UI
    'portfolio.gallery.filter.all': 'All',
    'portfolio.gallery.filter.filter': 'Filter',
    'portfolio.gallery.filter.tank': 'Tank',
    'portfolio.gallery.filter.env': 'Environment',
    'portfolio.gallery.stats.total': 'Total',
    'portfolio.gallery.stats.images': 'work photos',
    'portfolio.gallery.stats.category': 'Category',
    'portfolio.gallery.loading': 'Loading...',
    'portfolio.gallery.load.more': 'Load More',
    'portfolio.gallery.title.modal': 'Gallery',
    
    // Portfolio Page - Project Descriptions (English)
    'portfolio.project.goseong.desc': 'Goseong Combined Natural Gas Power Plant Silencer and Filter System Construction Project',
    'portfolio.project.andong.desc': 'Andong Combined Cycle Power Plant Unit 2 Exhaust Silencer and Structure System',
    'portfolio.project.waste.tank.desc': 'SK Hynix Waste Storage Tank System Construction',
    'portfolio.project.kleannara.desc': 'Kleannara Cheongju Incineration Facility Silencer System',
    'portfolio.project.datacenter.desc': 'Bupyeong Data Center Diesel Generator Exhaust Silencer System',
    'portfolio.project.turkistan.desc': 'Kazakhstan Turkistan Combined Cycle Power Plant Condensate Drain Tank',
    'portfolio.project.rgo.desc': 'Recycled Green Oil Light Naphtha Coalescer and Heavy Oil Filter',
    'portfolio.project.shuaibah.desc': 'Saudi Arabia Shu\'aiba 3 Independent Water Treatment Facility Donor Loading Filter',
    'portfolio.project.jafurah.desc': 'Saudi Arabia Jafurah Gas Supply System Condensate Drain Tank',
    'portfolio.project.activated.carbon.desc': 'Daegu Metropolitan City Activated Carbon Regeneration Facility Hopper and Structure',
    'portfolio.project.bangladesh.desc': 'Bangladesh Meghnaghat 718MW Combined Cycle Power Plant Steam Blowout Silencer',
    'portfolio.project.posco.desc': 'POSCO Pohang 3, 4 Blast Furnace Stack Silencer Maintenance',
    
    // Portfolio Page - Project Achievements (English)
    'portfolio.project.goseong.achievement1': 'Manufactured 5 sets of large silencers ranging from 40-inch to 2-inch scale',
    'portfolio.project.goseong.achievement2': 'Designed various specification silencers including ID3200X9150L, ID2200X4040L',
    'portfolio.project.goseong.achievement3': 'Achieved power plant environmental noise standards and stability',
    
    'portfolio.project.andong.achievement1': 'Designed and manufactured 14-inch scale exhaust silencers',
    'portfolio.project.andong.achievement2': 'Manufactured large silencers OD1853 X7270L',
    'portfolio.project.andong.achievement3': 'Built 6m X 6m x 25m scale structures',
    
    'portfolio.project.waste.tank.achievement1': 'Manufactured 3 sets of storage tanks W2062 X D1262 X 4300L scale',
    'portfolio.project.waste.tank.achievement2': 'Built 1-inch to 18-inch piping systems',
    'portfolio.project.waste.tank.achievement3': 'Secured corrosion resistance with SS275 material',
    
    'portfolio.project.kleannara.achievement1': 'Manufactured silencers OD1400 X 3450L scale',
    'portfolio.project.kleannara.achievement2': 'Secured durability with A516-60 material application',
    'portfolio.project.kleannara.achievement3': 'Built 2-inch to 8-inch piping systems',
    
    'portfolio.project.datacenter.achievement1': 'Manufactured 2 sets of exhaust silencers 750A, 500A scale',
    'portfolio.project.datacenter.achievement2': 'Designed large silencers OD1800x4500TL, OD1500x3200TL',
    'portfolio.project.datacenter.achievement3': 'Achieved data center noise standards',
    
    'portfolio.project.turkistan.achievement1': 'Manufactured 5 sets of condensate drain tanks applying GOST standards',
    'portfolio.project.turkistan.achievement2': 'Manufactured high-quality tanks with A516-70 material',
    'portfolio.project.turkistan.achievement3': 'Successfully performed overseas project',
    
    'portfolio.project.rgo.achievement1': 'Filter systems ID1600x1500TL, ID14"x1800TL scale',
    'portfolio.project.rgo.achievement2': 'Manufactured 4 sets of light naphtha coalescers and heavy oil filters',
    'portfolio.project.rgo.achievement3': 'Designed high-performance filters with A516-70 material',
    
    'portfolio.project.shuaibah.achievement1': 'Built premium filter systems with 316SS material',
    'portfolio.project.shuaibah.achievement2': 'Manufactured filters ID3"x300TLx2Set scale',
    'portfolio.project.shuaibah.achievement3': 'Successfully performed large overseas project',
    
    'portfolio.project.jafurah.achievement1': 'Manufactured condensate drain tanks 9T/17T scale',
    'portfolio.project.jafurah.achievement2': 'Designed high-quality tanks with A516-70 material',
    'portfolio.project.jafurah.achievement3': 'Performed Saudi Arabia ARAMCO project',
    
    'portfolio.project.activated.carbon.achievement1': 'Manufactured 6 sets of hoppers ID1200x1000TL scale',
    'portfolio.project.activated.carbon.achievement2': 'Premium hopper systems with A240-304 material',
    'portfolio.project.activated.carbon.achievement3': 'Built environmental facility silencers and structures',
    
    'portfolio.project.bangladesh.achievement1': 'Manufactured large steam blowout silencers 24-inch scale',
    'portfolio.project.bangladesh.achievement2': 'Designed silencers ID3000x9000TL scale',
    'portfolio.project.bangladesh.achievement3': 'Large silencer systems 9T/17T/18.5Tons scale',
    
    'portfolio.project.posco.achievement1': 'Large stack silencers OD3009x13297L scale, 2 sets',
    'portfolio.project.posco.achievement2': 'Large silencer systems 15.5-ton scale',
    'portfolio.project.posco.achievement3': 'Maintenance of existing facilities and performance improvement',
    
    // Privacy Policy Page
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Check Kyoungin Engineering\'s personal information protection policy',
    'privacy.section1.title': '1. Purpose of Personal Information Processing',
    'privacy.section1.content': 'Kyoungin Engineering processes personal information for the following purposes and does not use it for purposes other than the following: - Customer inquiry and consultation processing - Service provision and contract fulfillment - Marketing and advertising utilization (with consent)',
    'privacy.section2.title': '2. Processing and Retention Period of Personal Information',
    'privacy.section2.content': 'The company processes and retains personal information within the personal information retention and use period agreed upon when collecting personal information from the information subject or within the period stipulated by law.',
    'privacy.section3.title': '3. Provision of Personal Information to Third Parties',
    'privacy.section3.content': 'The company processes personal information only within the scope specified in Article 1 (Purpose of Personal Information Processing) and provides personal information to third parties only in cases that fall under Article 17 and Article 18 of the Personal Information Protection Act, such as consent from the information subject and special provisions of laws.',
    'privacy.section4.title': '4. Rights and Obligations of Information Subject and Exercise Method',
    'privacy.section4.content': 'The information subject may request the company to access, correct, delete, or suspend processing of personal information at any time, and the company will take measures without delay.',
    'privacy.section5.title': '5. Safety Measures for Personal Information',
    'privacy.section5.content': 'The company takes the following safety measures in accordance with Article 29 of the Personal Information Protection Act: - Encryption of personal information - Technical measures against hacking - Access restrictions on personal information',
    'privacy.contact.title': 'Personal Information Protection Officer',
    'privacy.contact.content': 'To oversee personal information processing tasks and handle complaints and damage relief related to personal information processing, we have designated the following personal information protection officer: - Name: Mac Kim - Position: Technical Sales Team Manager - Contact: 031-987-6127',
    
    // Terms of Service Page
    'terms.title': 'Terms of Service',
    'terms.subtitle': 'Check Kyoungin Engineering website terms of service',
    'terms.section1.title': 'Article 1 (Purpose)',
    'terms.section1.content': 'This agreement aims to regulate rights, obligations, and responsibilities between the company and users, and other necessary matters related to the use of website services provided by Kyoungin Engineering (hereinafter "Company").',
    'terms.section2.title': 'Article 2 (Definitions)',
    'terms.section2.content': 'The definitions of terms used in this agreement are as follows: 1. "Service" means the website and related services provided by the company. 2. "User" means a customer who accesses the company\'s service, enters into a usage agreement with the company according to this agreement, and uses the services provided by the company.',
    'terms.section3.title': 'Article 3 (Effectiveness and Changes of Agreement)',
    'terms.section3.content': 'This agreement becomes effective by posting it on the service screen or notifying users by other means. The company may change this agreement within the scope that does not violate relevant laws and regulations when necessary.',
    'terms.section4.title': 'Article 4 (Service Provision)',
    'terms.section4.content': 'The company performs the following tasks: 1. Company information and service introduction 2. Customer inquiry and consultation processing 3. Quote requests and processing 4. Other tasks determined by the company',
    'terms.section5.title': 'Article 5 (Service Suspension)',
    'terms.section5.content': 'The company may temporarily suspend service provision when there are reasons such as maintenance, replacement, and failure of information and communication facilities such as computers, or communication interruption.',
    'terms.contact.title': 'Contact',
    'terms.contact.content': 'If you have any questions about this agreement, please contact us at: - Phone: 031-987-6127 - Email: bhkim@kieng.co.kr',
    
    // Sitemap Page
    'sitemap.title': 'Sitemap',
    'sitemap.subtitle': 'Check all pages of Kyoungin Engineering website at a glance',
    'sitemap.main.title': 'Main Pages',
    'sitemap.services.title': 'Services',
    'sitemap.company.title': 'Company Information',
    'sitemap.legal.title': 'Legal Notice',
    'sitemap.quickLinks.title': 'Quick Links',
    'sitemap.quickLinks.contact': 'Contact',
    'sitemap.quickLinks.contactDesc': 'Inquiry and Consultation',
    'sitemap.quickLinks.quote': 'Get Quote',
    'sitemap.quickLinks.quoteDesc': 'Request Quote',
    'sitemap.quickLinks.portfolio': 'Portfolio',
    'sitemap.quickLinks.portfolioDesc': 'Project Achievements',
  }
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ko')

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
